Add models/task
No-Country/s13-20-n-python-django pull request #5
Opened 2024-02-14 02:08 UTC by Nahuel-a

2024-02-14 23:49 UTC, suspiciousRaccoon commented on app/tasks/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
Puede que queramos meterle models.SET_NULL para evitar que se pierdan datos

2024-02-14 23:50 UTC, suspiciousRaccoon commented on app/tasks/models.py
> +    description = models.CharField(max_length=255, black=True)
Cambiar TextField.

2024-02-14 23:50 UTC, suspiciousRaccoon commented on app/tasks/models.py
> +    name = models.CharField(max_length=100, blank=True)
Cambiar a max_length=255

2024-02-14 23:51 UTC, suspiciousRaccoon commented on app/tasks/models.py
> +    # list = models.ForeignKey(List, on_delete=models.SET_NULL, null=True)
Acá sí queremos models.CASCADE. Si el usuario quiere conservar el task lo puede mover a otro List.

2024-02-14 23:52 UTC, suspiciousRaccoon commented on app/tasks/models.py
> +    file = models.ImageField(blank=True)
No me quedó claro si al final los files podían ser de cualquier tipo o eran solamente imágenes. Dependiendo de esto tenemos que cambiar el field.

2024-02-14 23:53 UTC, suspiciousRaccoon commented on app/tasks/models.py
> +    task = models.ForeignKey(Task, on_delete=models.SET_NULL, blank=True)
Si se borra la Task no tiene sentido que el comentario se quede en la DB. Lo cambiaría por models.CASCADE.

2024-02-14 23:54 UTC, suspiciousRaccoon commented on pyproject.toml
> +pillow = "10.2"
Falta el constraint de versión. Es importante que esté para las alertas de dependabot.

2024-02-14 23:54 UTC, suspiciousRaccoon requested changes

2024-02-14 23:54 UTC, suspiciousRaccoon commented on app/tasks/models.py
Faltan los modelos de Board y List. Al menos que los queramos meter en otra aplicación.

2024-02-15 00:11 UTC, Nahuel-a commented on app/tasks/models.py
Eso queria preguntar, tenia pensado hacer otras api para los modelos que faltan, pero tampoco estaba muy seguro de cuales

2024-02-15 00:13 UTC, Nahuel-a commented on pyproject.toml
> +pillow = "10.2"
Yo cuando agrego algo al poetry pongo el comando "poetry add" , tendria q poner un comando extra para agregar los constrain verdad?

2024-02-15 00:20 UTC, suspiciousRaccoon commented on app/tasks/models.py
Creo que lo mejor va a ser que los metamos en la misma aplicación. Si hacemos una API podemos dividir los serializers en varios módulos. No estoy tan seguro sobre los modelos de Project y Milestone.

2024-02-15 00:20 UTC, suspiciousRaccoon commented on pyproject.toml
> +pillow = "10.2"
Raro, generalmente te lo agrega con ese constraint. `poetry add pillow` debería de haberlo puesto : /.

2024-02-15 02:27 UTC, suspiciousRaccoon commented on app/tasks/models.py
> +    complete = models.BooleanField(default=False)
Falta field m2m usando MilestoneTask como tabla, o alternativamente sacar la tabla y dejar que la cree django

2024-02-15 03:02 UTC, Nahuel-a commented on app/tasks/models.py
> +    complete = models.BooleanField(default=False)
Perdon mi ignoracia, pero no comprendi.
La tabla/modelo MilstoneTask esta creada, no se si es eso a lo que te referis.

2024-02-15 03:48 UTC, suspiciousRaccoon commented on app/tasks/models.py
> +    complete = models.BooleanField(default=False)
Django necesita un field m2m en el modelo para las relaciones inversas. Por ejemplo:
```python
from django.db import models


class Publication(models.Model):
    title = models.CharField(max_length=30)

class Article(models.Model):
    headline = models.CharField(max_length=100)
    publications = models.ManyToManyField(Publication)
````
Django crea la tabla PublicationArticle automáticamente.
Si queremos especificar la tabla PublicationArticle manualmente tenemos que agregar un [argumento](https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.ManyToManyField.through)
```python
class Publication(models.Model):
    title = models.CharField(max_length=30)

class PublicationArticle(models.Model):
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    more_info = models.CharField(max_length=255)

class Article(models.Model):
    headline = models.CharField(max_length=100)
    publications = models.ManyToManyField(Publication, through="Membership")
```
[Más info](https://docs.djangoproject.com/en/5.0/topics/db/models/#extra-fields-on-many-to-many-relationships)

2024-02-15 15:08 UTC, gjaguirre reviewed
OK .

2024-02-16 02:09 UTC, suspiciousRaccoon commented
@Nahuel-a Falta el field m2m en el modelo de `Milestone`, después de eso podemos mergear.

2024-02-16 02:35 UTC, suspiciousRaccoon approved these changes
lgtm

2024-02-16 02:35 UTC, merged